name: multas_ar_workspace
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

workspace:
  - apps/mobile
  - packages/legal_db
  - packages/core
  - packages/domain
  - packages/data_local
  - packages/ocr
  - packages/pdf_generator
  - packages/ui_kit

dev_dependencies:
  melos: ^8.9.0
